# Contact information
agency: dems
year: 2017
title: dems
email: info@dems-agency.com
address: Jardines de veracruz, del restaurante Tauro 2 cuadras abajo y 15 varas al oeste, casa  I16
phone: tel:+50522505978
website: http://www.dems-agency.com
facebook: https://www.facebook.com/ demsagency
twitter: https://twitter.com/
instagram: https://www.instagram.com/
youtube: https://www.youtube.com/
linkedin: https://www.linkedin.com/

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dems-agency.github.io/web/" # the base hostname & protocol for your site, e.g. http://example.com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
